'use strict';

Object.assign(Jam.I18n.defaults, {

    'Access items': 'Элементы доступа',
    'Actions': 'Действия',
    'All': 'Все',
    'Allow': 'Разрешить',
    'Assignment': 'Назначение',
    'Assignment rule': 'Правило назначения',
    'Assignment rules': 'Правила назначений',
    'Assignments': 'Назначения',
    'Attribute': 'Атрибут',

    'Background': 'Фоновый',

    'Child items': 'Дочерние элементы',
    'Child permissions': 'Дочерние разрешения',
    'Child roles': 'Дочерние роли',
    'Children': 'Наследники',
    'Class': 'Класс',
    'Close': 'Закрыть',
    'Code name': 'Кодовое имя',
    'Configuration': 'Конфигурация',
    'Configuration for creating a message template': 'Конфигурация для создания шаблона сообщения',
    'Content': 'Содержание',
    'Create assignment rule': 'Создать правило назначения',
    'Create event handler': 'Создать обработчик события',
    'Create index': 'Создать индекс',
    'Create item': 'Создать элемент',
    'Create listener': 'Создать слушателя',
    'Create notification': 'Создать уведомление',
    'Create task': 'Создать задачу',
    'Create permission': 'Создать разрешение',
    'Create permission target': 'Создать цель разрешения',
    'Create message': 'Создать сообщение',
    'Create metadata permission': 'Создать разрешение метаданных',
    'Create popup notification': 'Создать всплывающее уведомление',
    'Create role': 'Создать роль',
    'Create rule': 'Создать правило',
    'Create user': 'Создать пользователя',
    'Create user filter': 'Создать фильтр пользователей',
    'Create user password': 'Создать пароль пользователя',

    'Database': 'База данных',
    'Date of the last session change': 'Дата последнего изменения сессии',
    'Delete expired sessions': 'Удалить истёкшие сессии',
    'Delete this index permanently?': 'Удалить этот индекс безвозвратно?',
    'Delivery methods': 'Методы доставки',
    'Deny': 'Запретить',
    'Disabled': 'Отключен',
    'Direct recipients': 'Прямые получатели',

    'Event': 'Событие',
    'Event handler': 'Обработчик события',
    'Event handlers': 'Обработчики событий',
    'Events': 'События',
    'Events triggered': 'События вызваны',
    'Excluded users': 'Исключенные пользователи',
    'Execute at server startup': 'Выполнить при старте сервера',
    'Execute indexing now?': 'Выполнить индексацию сейчас?',
    'Execute notification': 'Выполнить уведомление',
    'Execute task': 'Выполнить задачу',
    'Execute this task now?': 'Выполнить эту задачу сейчас?',
    'Expired password': 'Пароль истёк',
    'Expired sessions have been deleted': 'Истёкшие сессии были удалены',
    'Expiry': 'Окончание',

    'File': 'Файл',
    'Filename': 'Имя файла',
    'Files': 'Файлы',
    'Filter': 'Фильтр',
    'Filter recipients when sending this notification': 'Фильтр получателей при отправке сообщения',

    'Hash': 'Хэш',
    'Handler': 'Обработчик',
    'Handlers': 'Обработчики',
    'Hierarchy': 'Иерархия',

    'If direct recipients empty on message sending then user filters from the notification will be used': 'Если нет прямых получателей при отправке сообщения, то будут использоваться фильтры пользователей из уведомления',
    'Included users': 'Включенные пользователи',
    'Indexing completed': 'Индексирование завершено',
    'Informing': 'Информирование',
    'Input new password to replace the current one': 'Введите новый пароль, чтобы изменить текущий',
    'Item': 'Элемент',
    'Items contained in the current': 'Элементы, содержащиеся в текущем элементе',
    'Items containing the current': 'Элементы, содержащие текущий элемент',
    'Items': 'Элементы',

    'Configuration of a job to be done when performing this task': 'Конфигурация работы, которая должна быть сделана при выполнении задачи',

    'Key': 'Ключ',
    'Keys': 'Ключи',

    'Links': 'Связи',
    'Listener': 'Слушатель',
    'Listeners': 'Слушатели',
    'Login session': 'Пользовательская сессия',
    'Login sessions': 'Пользовательские сессии',
    'Logs': 'Логи',

    'Main': 'Основные',
    'Maximum number of task launches (zero is unlimited)': 'Максимальное количество запусков задачи (ноль - без ограничений)',
    'Media type': 'Тип медиа',
    'Message': 'Сообщение',
    'Message sent': 'Сообщение отправлено',
    'Message template configuration': 'Конфигурация шаблона сообщения',
    'Messages': 'Сообщения',
    'Messages created by this notification': 'Сообщения созданные по данному уведомлению',
    'Message recipients for this notification': 'Получатели данного уведомления',
    'Metadata entities to which the permission applies': 'Сущности метаданных к которым применяется разрешение',
    'Metadata items': 'Элементы метаданных',
    'Metadata permission': 'Разрешение метаданных',
    'Metadata permissions': 'Разрешения метаданных',
    'Methods': 'Методы',
    'Model': 'Модель',

    'Name': 'Название',
    'Navigation section': 'Секция навигация',
    'Navigation node': 'Пункт навигация',
    'Notification': 'Уведомление',
    'Notification message': 'Сообщение',
    'Notification message created': 'Сообщение создано',
    'Notification messages': 'Сообщения',
    'Notifications': 'Уведомления',

    'Object': 'Объект',
    'Observer restarted': 'Наблюдатель перезапущен',
    'Options': 'Опции',
    'Owners': 'Владельцы',

    'Params': 'Параметры',
    'Parent items': 'Родительские элементы',
    'Parent permissions': 'Родительские разрешения',
    'Parent roles': 'Родительские роли',
    'Parents': 'Родители',
    'Passwords': 'Пароли',
    'Pending': 'В ожидании',
    'Period': 'Период',
    'Permission': 'Разрешение',
    'Permission target': 'Цель разрешения',
    'Permissions': 'Разрешения',
    'Popup': 'Всплывающее',
    'Popup notification': 'Всплывающее уведомление',
    'Popup notifications': 'Всплывающие уведомления',

    'Raw files': 'Файлы',
    'Read': 'Прочитано',
    'Recipient configuration': 'Конфигурация получателей',
    'Recipient filters': 'Фильтры получателей',
    'Records are created when files are uploaded.<br>Records without an owner are periodically deleted by <code>deleteExpiredFiles</code> task. The owner is an object of a class that implements the file behavior.': 'Записи создаются в момент загрузки файлов.<br>Записи без владельца периодически удаляются задачей <code>deleteExpiredFiles</code>. Владельцем является объект класса, реализующего файловое поведение.',
    'Refresh scheduler': 'Обновить планировщик',
    'Refuse to drop the system index': 'Отказать в удалении системного индекса',
    'Rename': 'Переименовать',
    'Repeats': 'Повторений',
    'Restart observer': 'Перезапустить наблюдателя',
    'Restart security': 'Перезапустить безопасность',
    'Role': 'Роль',
    'Role will be automatically assigned to users for whom at least one of these rules is allowed': 'Роль будет автоматические назначена пользователям, для которых разрешится хотя бы одно из правил',
    'Roles': 'Роли',
    'Route': 'Маршрут',
    'Rule': 'Правило',
    'Rules': 'Правила',
    'Rules check conditions for automatically assigning the specified roles (permissions) to users': 'Правила проверяют условия для автоматического назначения указанных ролей (разрешений) пользователям',
    'Rules check whether to use this permission': 'Правила проверяют, следует ли использовать данное разрешение',
    'Rules check whether to use this role': 'Правила проверяют, следует ли использовать данную роль',
    'Rules determine the availability of permissions (roles) that contain them': 'Правила определяют доступность разрешений (ролей), которые их содержат',
    'Run task': 'Выполнить задачу',

    'S3 file': 'Файл S3',
    'S3 files': 'Файлы S3',
    'Save': 'Сохранить',
    'Security': 'Безопасность',
    'Security restarted': 'Безопасность перезапущена',
    'Send message': 'Отправить сообщение',
    'Sent at': 'Отправлено',
    'Separate events with comma': 'Разделять события запятой',
    'Separate with comma': 'Разделять запятой',
    'Sessions': 'Сессии',
    'Scheduler refreshed': 'Планировшщик обновлен',
    'Size': 'Размер',
    'Spawn configuration': 'Конфигурация создания',
    'Start date': 'Дата начала',
    'Start every day at this time': 'Начинать каждый день в это время',
    'Start time': 'Время начала',
    'Startup': 'Стартовая',
    'Stop on fail': 'Остановить при ошибке',
    'Stop running task on job error': 'Прекратить выполнение задачи в случае ошибки',

    'Table': 'Таблица',
    'Tables': 'Таблицы',
    'Target': 'Цель',
    'Targets': 'Цели',
    'Task': 'Задача',
    'Task executed': 'Задача выполнена',
    'Task repetition period (seconds or ISO 8601 format). Zero is non-repeatability': 'Период повторения задачи (секунды или формат ISO 8601). Ноль - неповторяемость',
    'Tasks': 'Задачи',
    'This file is associated with some owner': 'Этот файл связан с владельцем',
    'Time': 'Время',
    'Title': 'Заголовок',
    'Transition': 'Переход',
    'Trigger': 'Триггер',
    'Trigger event': 'Вызвать событие',
    'Trigger events': 'Вызвать события',
    'Type': 'Тип',
    'Types': 'Типы',

    'Unique': 'Уникальный',
    'Unlock at': 'Разблокировать после',
    'Update item': 'Изменить элемент',
    'Uploaded files': 'Загруженные файлы',
    'Uploads': 'Загрузки',
    'User': 'Пользователь',
    'User filter': 'Фильтр пользователей',
    'User filter configuration for selecting recipients when creating a message': 'Конфигурация фильтра пользователей для выбора получателей при создании сообщения',
    'User filters': 'Фильтры пользователей',
    'User password': 'Пароль пользователя',
    'Users': 'Пользователи',

    'Verified': 'Проверен',
    'View': 'Представление',
});

Jam.I18n.rbac = {

    'Actions': 'Действия',
    'All': 'Все',

    'Create': 'Создавать',

    'Delete': 'Удалять',

    'Read': 'Читать',

    'Update': 'Изменять',

    'View history': 'Просмотр истории'
};

Jam.I18n.user = {

    'Name': 'Имя'
};