'use strict';

Object.assign(Jam.I18n.defaults, {

    'Access items': 'Элементы доступа',
    'Actions': 'Действия',
    'All': 'Все',
    'Allow': 'Разрешить',
    'Assignment': 'Назначение',
    'Assignment rule': 'Правило назначения',
    'Assignment rules': 'Правила назначений',
    'Assignments': 'Назначения',
    'Attribute': 'Атрибут',

    'Background': 'Фоновый',

    'Child items': 'Дочерние элементы',
    'Child permissions': 'Дочерние разрешения',
    'Child roles': 'Дочерние роли',
    'Children': 'Наследники',
    'Class': 'Класс',
    'Close': 'Закрыть',
    'Code name': 'Кодовое имя',
    'Configuration': 'Конфигурация',
    'Content': 'Содержание',
    'Create index': 'Создать индекс',
    'Create item': 'Создать элемент',
    'Create listener': 'Создать слушателя',
    'Create notice': 'Создать уведомление',
    'Create task': 'Создать задачу',
    'Create permission': 'Создать разрешение',
    'Create permission target': 'Создать цель разрешения',
    'Create metadata permission': 'Создать разрешение метаданных',
    'Create popup notification': 'Создать всплывающее уведомление',
    'Create role': 'Создать роль',
    'Create rule': 'Создать правило',
    'Create user': 'Создать пользователя',
    'Create user filter': 'Создать фильтр пользователей',
    'Create user password': 'Создать пароль пользователя',

    'Database': 'База данных',
    'Deny': 'Запретить',
    'Disabled': 'Отключен',

    'Editor': 'Редактор',
    'Event': 'Событие',
    'Event handler': 'Обработчик события',
    'Event handlers': 'Обработчики событий',
    'Events': 'События',
    'Excluded users': 'Исключенные пользователи',
    'Execute at server startup': 'Выполнить при старте сервера',
    'Execute indexing now?': 'Выполнить индексацию сейчас?',
    'Execute notice': 'Выполнить уведомление',
    'Execute task': 'Выполнить задачу',
    'Execute this task now?': 'Выполнить эту задачу сейчас?',
    'Expired password': 'Пароль истек',

    'File': 'Файл',
    'Filename': 'Имя файла',
    'Files': 'Файлы',
    'Filter': 'Фильтр',

    'Handler': 'Обработчик',
    'Handlers': 'Обработчики',
    'Hierarchy': 'Иерархия',

    'Included users': 'Включенные пользователи',
    'Indexing completed': 'Индексирование завершено',
    'Informing': 'Информирование',
    'Input new password to replace the current one': 'Введите новый пароль, чтобы изменить текущий',
    'Item': 'Элемент',
    'Items contained in the current': 'Элементы, содержащиеся в текущем элементе',
    'Items containing the current': 'Элементы, содержащие текущий элемент',
    'Items': 'Элементы',

    'Key': 'Ключ',
    'Keys': 'Ключи',

    'Links': 'Связи',
    'Listener': 'Слушатель',
    'Listeners': 'Слушатели',
    'Logs': 'Логи',

    'Main': 'Основные',
    'Message': 'Сообщение',
    'Message recipients for this notice': 'Получатели сообщений по данному уведомлению',
    'Message sent': 'Сообщение отправлено',
    'Message users': 'Пользователи сообщений',
    'Messages': 'Сообщения',
    'Messages created by this notice': 'Сообщения созданные по данному увемлению',
    'Metadata items': 'Элементы метаданных',
    'Metadata permission': 'Разрешение метаданных',
    'Metadata permissions': 'Разрешения метаданных',
    'Methods': 'Методы',
    'MIME type': 'MIME тип',
    'Model': 'Модель',

    'Name': 'Название',
    'Navigation section': 'Секция навигация',
    'Navigation node': 'Пункт навигация',
    'Notice': 'Уведомление',
    'Notice message': 'Сообщение',
    'Notice message created': 'Сообщение создано',
    'Notice messages': 'Сообщения',
    'Notices': 'Уведомления',
    'Notifications': 'Уведомления',

    'Observer restarted': 'Наблюдатель перезапущен',
    'Object': 'Объект',
    'Options': 'Опции',
    'Owners': 'Владельцы',

    'Params': 'Параметры',
    'Parent items': 'Родительские элементы',
    'Parent permissions': 'Родительские разрешения',
    'Parent roles': 'Родительские роли',
    'Parents': 'Родители',
    'Passwords': 'Пароли',
    'Pending': 'В ожидании',
    'Period': 'Период',
    'Permission': 'Разрешение',
    'Permission target': 'Цель разрешения',
    'Permissions': 'Разрешения',
    'Popup': 'Всплывающее',
    'Popup notification': 'Всплывающее уведомление',
    'Popup notifications': 'Всплывающие уведомления',

    'Read': 'Прочитано',
    'Recipient filters': 'Фильтры получателей',
    'Refresh scheduler': 'Обновить планировщик',
    'Refuse to drop the system index': 'Отказать в удалении системного индекса',
    'Reindex': 'Переиндексировать',
    'Rename': 'Переименовать',
    'Repeats': 'Повторений',
    'Restart observer': 'Перезапустить наблюдателя',
    'Restart security': 'Перезапустить безопасность',
    'Role': 'Роль',
    'Role will be assigned if at least one rule is allowed': 'Роль будет назначена, если разрешится хотя бы одно правило',
    'Roles': 'Роли',
    'Route': 'Маршрут',
    'Rule': 'Правило',
    'Rules': 'Правила',
    'Run task': 'Выполнить задачу',

    'Save': 'Сохранить',
    'Seconds or ISO 8601 format': 'Секунды или формат ISO 8601',
    'Security': 'Безопасность',
    'Security restarted': 'Безопасность перезапущена',
    'Send message': 'Отправить сообщение',
    'Sent at': 'Отправлено',
    'Separate with comma': 'Разделять запятой',
    'Size': 'Размер',
    'Spawn configuration': 'Конфигурация создания',
    'Start date': 'Дата начала',
    'Start every day at this time': 'Начинать каждый день в это время',
    'Start time': 'Время начала',
    'Startup': 'Стартовая',
    'State': 'Состояние',
    'Stop on fail': 'Остановить при ошибке',
    'Stop running task on job error': 'Прекратить выполнение задачи в случае ошибки',

    'Table': 'Таблица',
    'Tables': 'Таблицы',
    'Target': 'Цель',
    'Targets': 'Цели',
    'Task': 'Задача',
    'Tasks': 'Задачи',
    'Time': 'Время',
    'Title': 'Заголовок',
    'Transition': 'Переход',
    'Trigger': 'Триггер',
    'Trigger event': 'Вызвать событие',
    'Trigger events': 'Вызвать события',
    'Type': 'Тип',
    'Types': 'Типы',

    'Unique': 'Уникальный',
    'Unlock at': 'Разблокировать после',
    'Update item': 'Изменить элемент',
    'Uploaded files': 'Загруженные файлы',
    'User': 'Пользователь',
    'User filter': 'Фильтр пользователей',
    'User filters': 'Фильтры пользователей',
    'User password': 'Пароль пользователя',
    'Users': 'Пользователи',

    'Verified': 'Проверен',
    'View': 'Представление',
});

Jam.I18n.rbac = {

    'Actions': 'Действия',
    'All': 'Все',

    'Create': 'Создавать',

    'Delete': 'Удалять',

    'Read': 'Читать',

    'Update': 'Изменять'
};

Jam.I18n.user = {

    'Name': 'Имя'
};